import { createContext, useContext, useState } from "react";

const LanguageContext = createContext(null);

const translations = {
  en: {
    home: "Home",
    hotels: "Hotels",
    rooms: "Rooms",
    contact: "Contact",
    bookNow: "Book Now",
    login: "Login",
    register: "Register",
    logout: "Logout",
    myBookings: "My Bookings",
    dashboard: "Dashboard",
    profile: "Profile",
    admin: "Admin Panel",
    heroTitle: "Experience Luxury, Feel at Home",
    heroSubtitle: "Book premium rooms at the best prices with instant confirmation, secure payments and 24x7 support.",
    searchPlaceholder: "Search hotel, city or location...",
    search: "Search",
    checkIn: "Check-in",
    checkOut: "Check-out",
    guests: "Guests",
    featuredHotels: "Featured Hotels",
    featuredSub: "Hand-picked stays loved by our guests",
    viewAll: "View all",
    perNight: "/ night",
    whyUs: "Why Choose Us",
    luxuryRooms: "Luxury Rooms",
    luxuryRoomsDesc: "Modern, comfortable rooms with premium amenities.",
    freeWifi: "Free Wi-Fi",
    freeWifiDesc: "High-speed internet in every room and lobby.",
    bestPrices: "Best Prices",
    bestPricesDesc: "Transparent pricing with smart deals & group discounts.",
    securePayment: "Secure Payments",
    securePaymentDesc: "Pay safely by card, UPI, net banking or wallet.",
    smartDeals: "Smart Deals",
    smartDealsSub: "Limited-time offers and discounts for you",
    useCode: "Use code",
    reviews: "Reviews",
    reviewsSub: "What our guests say about us",
    submitReview: "Write a review",
    rating: "Rating",
    comment: "Your comment",
    addReview: "Submit Review",
    yourRating: "Your rating",
    location: "Location",
    amenities: "Amenities",
    description: "About this hotel",
    weather: "Weather in",
    map: "Location Map",
    availableRooms: "Available Rooms",
    total: "Total",
    nights: "nights",
    roomType: "Room Type",
    mobile: "Mobile Number",
    fullName: "Full Name",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    forgotPassword: "Forgot password?",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    price: "Price",
    groupBooking: "Group booking (2+ rooms gets 10% off)",
    numberOfRooms: "Number of rooms",
    continuePayment: "Continue to Payment",
    payNow: "Pay Now",
    cardNumber: "Card Number",
    cardName: "Name on Card",
    expiry: "Expiry (MM/YY)",
    cvv: "CVV",
    paymentMethod: "Payment Method",
    paymentSuccessful: "Payment Successful",
    bookingSuccess: "Booking Confirmed!",
    bookingRef: "Booking Reference",
    viewMyBookings: "View My Bookings",
    bookAnother: "Book Another Room",
    loadMore: "Loading...",
    noResults: "No results found",
    noHotels: "No hotels found. Try different filters.",
    welcome: "Welcome",
    adminDashboard: "Dashboard",
    manageHotels: "Hotels",
    manageRooms: "Rooms",
    manageBookings: "Bookings",
    manageUsers: "Users",
    manageReviews: "Reviews",
    manageDeals: "Deals",
    liveChat: "Live Chat",
    totalRevenue: "Total Revenue",
    totalBookings: "Total Bookings",
    totalUsers: "Total Users",
    totalReviews: "Total Reviews",
    recentBookings: "Recent Bookings",
    status: "Status",
    actions: "Actions",
    delete: "Delete",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    create: "Create",
    name: "Name",
    yes: "Yes",
    no: "No",
    fraudFlagged: "Fraud Flagged",
    aiAssistant: "AI Assistant",
    chatWithUs: "Chat with our AI assistant",
    typeMessage: "Type your message...",
    online: "Online",
    offline: "Offline",
    notifications: "Notifications",
    markAllRead: "Mark all as read",
    noNotifications: "No notifications",
    language: "Language",
    needHelp: "Need help?",
    experience: "Experience",
  },
  hi: {
    home: "होम",
    hotels: "होटल",
    rooms: "कमरे",
    contact: "संपर्क",
    bookNow: "अभी बुक करें",
    login: "लॉगिन",
    register: "रजिस्टर",
    logout: "लॉगआउट",
    myBookings: "मेरी बुकिंग",
    dashboard: "डैशबोर्ड",
    profile: "प्रोफ़ाइल",
    admin: "एडमिन पैनल",
    heroTitle: "लग्जरी का अनुभव, घर जैसा एहसास",
    heroSubtitle: "सर्वोत्तम दरों पर प्रीमियम कमरे बुक करें — तुरंत पुष्टि, सुरक्षित भुगतान और 24x7 सहायता के साथ।",
    searchPlaceholder: "होटल, शहर या स्थान खोजें...",
    search: "खोजें",
    checkIn: "चेक-इन",
    checkOut: "चेक-आउट",
    guests: "मेहमान",
    featuredHotels: "विशेष होटल",
    featuredSub: "हमारे मेहमानों द्वारा पसंद किए गए चुनिंदा स्टे",
    viewAll: "सभी देखें",
    perNight: "/ रात",
    whyUs: "हमें क्यों चुनें",
    luxuryRooms: "लक्ज़री कमरे",
    luxuryRoomsDesc: "प्रीमियम सुविधाओं के साथ आधुनिक, आरामदायक कमरे।",
    freeWifi: "मुफ़्त वाई-फ़ाई",
    freeWifiDesc: "हर कमरे और लॉबी में हाई-स्पीड इंटरनेट।",
    bestPrices: "सर्वोत्तम दरें",
    bestPricesDesc: "स्मार्ट ऑफ़र और ग्रुप छूट के साथ पारदर्शी मूल्य।",
    securePayment: "सुरक्षित भुगतान",
    securePaymentDesc: "कार्ड, UPI, नेट बैंकिंग या वॉलेट से सुरक्षित भुगतान।",
    smartDeals: "स्मार्ट ऑफ़र",
    smartDealsSub: "आपके लिए सीमित समय के ऑफ़र और छूट",
    useCode: "कोड उपयोग करें",
    reviews: "समीक्षाएँ",
    reviewsSub: "हमारे बारे में हमारे मेहमान क्या कहते हैं",
    submitReview: "समीक्षा लिखें",
    rating: "रेटिंग",
    comment: "आपकी टिप्पणी",
    addReview: "समीक्षा सबमिट करें",
    yourRating: "आपकी रेटिंग",
    location: "स्थान",
    amenities: "सुविधाएँ",
    description: "इस होटल के बारे में",
    weather: "मौसम —",
    map: "स्थान मानचित्र",
    availableRooms: "उपलब्ध कमरे",
    total: "कुल",
    nights: "रातें",
    roomType: "कमरे का प्रकार",
    mobile: "मोबाइल नंबर",
    fullName: "पूरा नाम",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    forgotPassword: "पासवर्ड भूल गए?",
    noAccount: "खाता नहीं है?",
    hasAccount: "पहले से खाता है?",
    price: "मूल्य",
    groupBooking: "ग्रुप बुकिंग (2+ कमरों पर 10% छूट)",
    numberOfRooms: "कमरों की संख्या",
    continuePayment: "भुगतान के लिए जारी रखें",
    payNow: "अभी भुगतान करें",
    cardNumber: "कार्ड नंबर",
    cardName: "कार्ड पर नाम",
    expiry: "समाप्ति (MM/YY)",
    cvv: "CVV",
    paymentMethod: "भुगतान विधि",
    paymentSuccessful: "भुगतान सफल",
    bookingSuccess: "बुकिंग की पुष्टि हो गई!",
    bookingRef: "बुकिंग संदर्भ",
    viewMyBookings: "मेरी बुकिंग देखें",
    bookAnother: "दूसरा कमरा बुक करें",
    loadMore: "लोड हो रहा है...",
    noResults: "कोई परिणाम नहीं मिला",
    noHotels: "कोई होटल नहीं मिला। अलग फ़िल्टर आज़माएँ।",
    welcome: "स्वागत है",
    adminDashboard: "डैशबोर्ड",
    manageHotels: "होटल",
    manageRooms: "कमरे",
    manageBookings: "बुकिंग",
    manageUsers: "उपयोगकर्ता",
    manageReviews: "समीक्षाएँ",
    manageDeals: "ऑफ़र",
    liveChat: "लाइव चैट",
    totalRevenue: "कुल राजस्व",
    totalBookings: "कुल बुकिंग",
    totalUsers: "कुल उपयोगकर्ता",
    totalReviews: "कुल समीक्षाएँ",
    recentBookings: "हाल की बुकिंग",
    status: "स्थिति",
    actions: "क्रियाएँ",
    delete: "हटाएँ",
    edit: "संपादित करें",
    save: "सहेजें",
    cancel: "रद्द करें",
    create: "बनाएँ",
    name: "नाम",
    fraudFlagged: "धोखाधड़ी चिह्नित",
    aiAssistant: "AI सहायक",
    chatWithUs: "हमारे AI सहायक से चैट करें",
    typeMessage: "अपना संदेश लिखें...",
    online: "ऑनलाइन",
    offline: "ऑफ़लाइन",
    notifications: "सूचनाएँ",
    markAllRead: "सभी पढ़ी हुई चिह्नित करें",
    noNotifications: "कोई सूचना नहीं",
    language: "भाषा",
    needHelp: "सहायता चाहिए?",
    experience: "अनुभव",
  },
  es: {
    home: "Inicio",
    hotels: "Hoteles",
    rooms: "Habitaciones",
    contact: "Contacto",
    bookNow: "Reservar",
    login: "Iniciar sesión",
    register: "Registrarse",
    logout: "Cerrar sesión",
    myBookings: "Mis reservas",
    dashboard: "Panel",
    profile: "Perfil",
    admin: "Panel admin",
    heroTitle: "Experimenta el lujo, siéntete como en casa",
    heroSubtitle: "Reserva habitaciones premium a los mejores precios con confirmación instantánea y pagos seguros.",
    searchPlaceholder: "Buscar hotel, ciudad o ubicación...",
    search: "Buscar",
    checkIn: "Entrada",
    checkOut: "Salida",
    guests: "Huéspedes",
    featuredHotels: "Hoteles destacados",
    featuredSub: "Estancias seleccionadas amadas por nuestros huéspedes",
    viewAll: "Ver todo",
    perNight: "/ noche",
    whyUs: "Por qué elegirnos",
    luxuryRooms: "Habitaciones de lujo",
    luxuryRoomsDesc: "Habitaciones modernas y cómodas con servicios premium.",
    freeWifi: "Wi-Fi gratis",
    freeWifiDesc: "Internet de alta velocidad en cada habitación.",
    bestPrices: "Mejores precios",
    bestPricesDesc: "Precios transparentes con ofertas y descuentos.",
    securePayment: "Pagos seguros",
    securePaymentDesc: "Pague con tarjeta, UPI, banca en línea o billetera.",
    smartDeals: "Ofertas inteligentes",
    smartDealsSub: "Ofertas y descuentos por tiempo limitado",
    useCode: "Usar código",
    reviews: "Reseñas",
    reviewsSub: "Lo que dicen nuestros huéspedes",
    submitReview: "Escribir reseña",
    rating: "Calificación",
    comment: "Tu comentario",
    addReview: "Enviar reseña",
    yourRating: "Tu calificación",
    location: "Ubicación",
    amenities: "Servicios",
    description: "Sobre este hotel",
    weather: "Clima en",
    map: "Mapa de ubicación",
    availableRooms: "Habitaciones disponibles",
    total: "Total",
    nights: "noches",
    roomType: "Tipo de habitación",
    mobile: "Teléfono",
    fullName: "Nombre completo",
    email: "Correo",
    password: "Contraseña",
    confirmPassword: "Confirmar contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    noAccount: "¿No tienes cuenta?",
    hasAccount: "¿Ya tienes cuenta?",
    price: "Precio",
    groupBooking: "Reserva grupal (10% de descuento en 2+ habitaciones)",
    numberOfRooms: "Número de habitaciones",
    continuePayment: "Continuar al pago",
    payNow: "Pagar ahora",
    cardNumber: "Número de tarjeta",
    cardName: "Nombre en la tarjeta",
    expiry: "Vencimiento (MM/AA)",
    cvv: "CVV",
    paymentMethod: "Método de pago",
    paymentSuccessful: "Pago exitoso",
    bookingSuccess: "¡Reserva confirmada!",
    bookingRef: "Referencia de reserva",
    viewMyBookings: "Ver mis reservas",
    bookAnother: "Reservar otra habitación",
    noResults: "Sin resultados",
    noHotels: "No se encontraron hoteles.",
    welcome: "Bienvenido",
    adminDashboard: "Panel",
    manageHotels: "Hoteles",
    manageRooms: "Habitaciones",
    manageBookings: "Reservas",
    manageUsers: "Usuarios",
    manageReviews: "Reseñas",
    manageDeals: "Ofertas",
    liveChat: "Chat en vivo",
    totalRevenue: "Ingresos totales",
    totalBookings: "Reservas totales",
    totalUsers: "Usuarios totales",
    totalReviews: "Reseñas totales",
    recentBookings: "Reservas recientes",
    status: "Estado",
    actions: "Acciones",
    delete: "Eliminar",
    edit: "Editar",
    save: "Guardar",
    cancel: "Cancelar",
    create: "Crear",
    name: "Nombre",
    fraudFlagged: "Fraude marcado",
    aiAssistant: "Asistente IA",
    chatWithUs: "Chatea con nuestro asistente IA",
    typeMessage: "Escribe tu mensaje...",
    online: "En línea",
    offline: "Desconectado",
    notifications: "Notificaciones",
    markAllRead: "Marcar todo como leído",
    noNotifications: "Sin notificaciones",
    language: "Idioma",
    needHelp: "¿Necesitas ayuda?",
    experience: "Experiencia",
  },
  fr: {
    home: "Accueil",
    hotels: "Hôtels",
    rooms: "Chambres",
    contact: "Contact",
    bookNow: "Réserver",
    login: "Connexion",
    register: "S'inscrire",
    logout: "Déconnexion",
    myBookings: "Mes réservations",
    dashboard: "Tableau de bord",
    profile: "Profil",
    admin: "Panneau admin",
    heroTitle: "Vivez le luxe, sentez-vous chez vous",
    heroSubtitle: "Réservez des chambres premium aux meilleurs prix avec confirmation instantanée et paiement sécurisé.",
    searchPlaceholder: "Rechercher hôtel, ville ou lieu...",
    search: "Rechercher",
    checkIn: "Arrivée",
    checkOut: "Départ",
    guests: "Voyageurs",
    featuredHotels: "Hôtels en vedette",
    featuredSub: "Séjours sélectionnés appréciés par nos clients",
    viewAll: "Tout voir",
    perNight: "/ nuit",
    whyUs: "Pourquoi nous choisir",
    luxuryRooms: "Chambres de luxe",
    luxuryRoomsDesc: "Chambres modernes et confortables avec équipements premium.",
    freeWifi: "Wi-Fi gratuit",
    freeWifiDesc: "Internet haut débit dans chaque chambre.",
    bestPrices: "Meilleurs prix",
    bestPricesDesc: "Prix transparents avec offres et réductions.",
    securePayment: "Paiements sécurisés",
    securePaymentDesc: "Payez par carte, UPI, virement ou portefeuille.",
    smartDeals: "Offres intelligentes",
    smartDealsSub: "Offres et réductions à durée limitée",
    useCode: "Utiliser le code",
    reviews: "Avis",
    reviewsSub: "Ce que nos clients disent de nous",
    submitReview: "Écrire un avis",
    rating: "Note",
    comment: "Votre commentaire",
    addReview: "Envoyer l'avis",
    yourRating: "Votre note",
    location: "Emplacement",
    amenities: "Équipements",
    description: "À propos de cet hôtel",
    weather: "Météo à",
    map: "Carte",
    availableRooms: "Chambres disponibles",
    total: "Total",
    nights: "nuits",
    roomType: "Type de chambre",
    mobile: "Téléphone",
    fullName: "Nom complet",
    email: "E-mail",
    password: "Mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    forgotPassword: "Mot de passe oublié ?",
    noAccount: "Pas de compte ?",
    hasAccount: "Déjà un compte ?",
    price: "Prix",
    groupBooking: "Réservation de groupe (10% de réduction sur 2+ chambres)",
    numberOfRooms: "Nombre de chambres",
    continuePayment: "Continuer vers le paiement",
    payNow: "Payer maintenant",
    cardNumber: "Numéro de carte",
    cardName: "Nom sur la carte",
    expiry: "Expiration (MM/AA)",
    cvv: "CVV",
    paymentMethod: "Méthode de paiement",
    paymentSuccessful: "Paiement réussi",
    bookingSuccess: "Réservation confirmée !",
    bookingRef: "Référence de réservation",
    viewMyBookings: "Voir mes réservations",
    bookAnother: "Réserver une autre chambre",
    noResults: "Aucun résultat",
    noHotels: "Aucun hôtel trouvé.",
    welcome: "Bienvenue",
    adminDashboard: "Tableau de bord",
    manageHotels: "Hôtels",
    manageRooms: "Chambres",
    manageBookings: "Réservations",
    manageUsers: "Utilisateurs",
    manageReviews: "Avis",
    manageDeals: "Offres",
    liveChat: "Chat en direct",
    totalRevenue: "Revenus totaux",
    totalBookings: "Réservations totales",
    totalUsers: "Utilisateurs totaux",
    totalReviews: "Avis totaux",
    recentBookings: "Réservations récentes",
    status: "Statut",
    actions: "Actions",
    delete: "Supprimer",
    edit: "Modifier",
    save: "Enregistrer",
    cancel: "Annuler",
    create: "Créer",
    name: "Nom",
    fraudFlagged: "Fraude signalée",
    aiAssistant: "Assistant IA",
    chatWithUs: "Discutez avec notre assistant IA",
    typeMessage: "Écrivez votre message...",
    online: "En ligne",
    offline: "Hors ligne",
    notifications: "Notifications",
    markAllRead: "Tout marquer comme lu",
    noNotifications: "Aucune notification",
    language: "Langue",
    needHelp: "Besoin d'aide ?",
    experience: "Expérience",
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem("hotel_lang") || "en");

  const changeLanguage = (code) => {
    setLang(code);
    localStorage.setItem("hotel_lang", code);
  };

  const t = (key) => translations[lang]?.[key] ?? translations.en[key] ?? key;

  const value = { lang, changeLanguage, t };
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);
